version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 217865333136.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t tutorial_fargate .
      - docker tag tutorial_fargate:latest 217865333136.dkr.ecr.us-east-1.amazonaws.com/tutorial_fargate:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 217865333136.dkr.ecr.us-east-1.amazonaws.com/tutorial_fargate:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"tutorial_fargate","imageUri":"217865333136.dkr.ecr.us-east-1.amazonaws.com/tutorial_fargate:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"217865333136.dkr.ecr.us-east-1.amazonaws.com/tutorial_fargate:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json